version: "3"

services:
  web:
    build:
      context: ./inside
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./inside:/code/
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
volumes:
  pgdata:
