version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ./inside
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./inside:/code/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
#      KAFKA_CREATE_TOPICS: "UploadFile:1:1,GetFile:1:1,TrackUpload:1:1,GetEmailContent:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
volumes:
  pgdata:
